engines:
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  nodesecurity:
    enabled: true
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 50
ratings:
  paths:
  - "**.js"
  - "**.md"
exclude_paths:
- "test"
- "LICENSE.md"
